;
; global custom
;
[custom]
build_flags =
  -I lib/OGM-HardwareConfig/include/
  -D OPENKNX_DUALCORE
  -D OPENKNX_MAX_LOG_MESSAGE_LENGTH=1024
  -D OPENKNX_LEDFUNC_BASE_PROG_UNCONFIGUREDSUPPORT

 
  
[custom_develop]
extends = custom
build_flags =
  ${custom.build_flags}
  ;-D OPENKNX_HEARTBEAT
  ; -D OPENKNX_HEARTBEAT_PRIO
  ; -D OPENKNX_RTT
  ; -D BUFFER_SIZE_UP=10240
  ; -D DEBUG_LOOP_TIME=10 ; will print a info when a loop took more than x ms.
  ; -D LOGIC_TRACE
  ; ; to see trace logs, they must match one of the 5 filters (TRACE_LOG1 .. TRACE_LOG2)
  ;"-D OPENKNX_TRACE1=OTAUpdateModule.*"
  ;"-D OPENKNX_TRACE2=Flash.*"
debug_build_flags = -ggdb3
  -O0

; this config block is for specifing options that are valid for all RP2040-based builds
[RP2040_custom]
extends = RP2040, custom
; platform = https://github.com/maxgerhardt/platform-raspberrypi.git#0b2e90a
; platform_packages = framework-arduinopico @ https://github.com/earlephilhower/arduino-pico/releases/download/2.7.3/rp2040-2.7.3.zip
; board = pico
build_flags = 
  -D SERIAL_DEBUG=Serial
  -D USE_KNX_DMA_UART=0
  -D USE_KNX_DMA_IRQ=0
  ; -D SERIAL_HF=Serial2
  -Wunused-variable

; this config block is for specifing options that are valid for all RP2040-based develop/debug builds
[RP2040_custom_develop]
extends = RP2040_develop, RP2040_custom, custom_develop
build_flags = 
  ${RP2040_develop.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_develop.build_flags}
debug_build_flags = 
  ${custom_develop.debug_build_flags}
  -O0 

[RP2040_custom_develop_TP]
extends = RP2040_custom_develop
build_flags = 
  ${RP2040_custom_develop.build_flags}
  ${KNX_TP.build_flags}
  -D OPENKNX_LED_TIME=info3Led


; this config block is for specifing options that are valid for all RP2040-based release builds
[RP2040_custom_releases]
extends = RP2040_releases, RP2040_custom, custom
build_flags = 
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom.build_flags}
  -D OPENKNX_DEBUG
  -O0


[RP2040_custom_releases_TP]
extends = RP2040_custom_releases
build_flags = 
  ${RP2040_custom_releases.build_flags}
  ${KNX_TP.build_flags}


[env:develop_OpenKNX_UP1_GW_2XUART]
extends = board_OpenKNX_UP1_GW_2XUART, RP2040_custom_develop_TP
build_flags =
  ${board_OpenKNX_UP1_GW_2XUART.build_flags}
  ${RP2040_custom_develop_TP.build_flags}


; ESP32
[custom_ESP32]
extends = ESP32, custom
monitor_filters = esp32_exception_decoder 
build_flags =
  ${ESP32.build_flags}
  -D KNX_FLASH_SIZE=0 #Setting not used because partion knx is used, but must be defined
  -D SERIAL_DEBUG=Serial
  -D KNX_FLASH_CALLBACK
  -D HVAC_DEBUG
build_unflags =
  -D LWIP_DONT_PROVIDE_BYTEORDER_FUNCTIONS
lib_deps = 
	#homespan/HomeSpan@2.1.0
  #HomeSpan=symlink://../HomeSpan

[custom_release_ESP32]
extends = ESP32_releases, custom, custom_ESP32
build_flags =
  ${ESP32_releases.build_flags}
  ${custom.build_flags}
  ${custom_ESP32.build_flags}
  -D OPENKNX_USB_EXCHANGE_IGNORE
  -D OPENKNX_LOOPTIME_WARNING=10

 
[RP2040_custom_releases_TP_2MB]
extends = RP2040_custom_releases_TP
build_flags = 
  ${RP2040_custom_releases_TP.build_flags}
 
[RP2040_custom_releases_TP_16MB]
extends = RP2040_custom_releases_TP
build_flags = 
  ${RP2040_custom_releases_TP.build_flags}

[develop_ESP32]
extends = ESP32_develop, custom_ESP32, custom_develop
build_flags =
  ${ESP32_develop.build_flags}
  ${custom_ESP32.build_flags}
  ${custom_develop.build_flags}
  -D LED_BUILTIN=2
  -D DEVELOPMENT

; -- UP1-GW-2xUART

[board_OpenKNX_UP1_GW_2XUART]
extends = 
build_flags =
  -D DEVICE_UP1_GW_2XUART


; ------ Waveshare ESP32-S3-Zero ------
[board_Waveshare_ESP32_S3_Zero]
extends = ESP32_4MB
board = esp32-s3-devkitm-1
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM
  -D PROG_BUTTON_PIN=0
 # -D OPENKNX_SERIALLED_ENABLE
 # -D OPENKNX_SERIALLED_PIN=21
 # -D OPENKNX_SERIALLED_COLOR_RED=50,0,0
 # -D OPENKNX_SERIALLED_COLOR_GREEN=0,35,0
 # -D OPENKNX_SERIALLED_COLOR_BLUE=0,0,63
 # -D OPENKNX_SERIALLED_COLOR_YELLOW=40,30,0
 # -D OPENKNX_SERIALLED_NUM=1
  -D PROG_LED_PIN=11
  -D PROG_LED_PIN_ACTIVE_ON=1
  -D PROG_LED_COLOR=OPENKNX_SERIALLED_COLOR_RED
  -D KNX_UART_NUM=1
  -D KNX_UART_RX_PIN=16
  -D KNX_UART_TX_PIN=17
  -D KNX_IP_WIFI
 


[env:develop_Waveshare_ESP32_S3_Zero_TP]
extends = ESP32_develop, custom_ESP32, custom_develop, board_Waveshare_ESP32_S3_Zero
monitor_speed = 921600
build_flags =
  ${KNX_TP.build_flags}

  ${ESP32_develop.build_flags}
  ${custom_ESP32.build_flags}
  ${custom_develop.build_flags}
  ${board_Waveshare_ESP32_S3_Zero.build_flags}
  -D DEVELOPMENT

[env:develop_Waveshare_ESP32_S3_Zero_TP_USB]
extends = ESP32_UPLOAD_USB, env:develop_Waveshare_ESP32_S3_Zero

; ------ AZDelivery ESP32 Board Dev Kit C V4 ------
[board_AZDelivery_DevKit_C_V4]
board = esp32dev
extends = ESP32_4MB
board_build.partitions = esp32_4mb.csv
build_flags =
  -D DEVICE_ID='"AZD-ESP32-DevKit-V4"'
  -D DEVICE_NAME='"AZDelivery ESP32 Board Dev Kit C V4"'
  -D PROG_BUTTON_PIN=0
  -D PROG_LED_PIN=2
  -D PROG_LED_PIN_ACTIVE_ON=1
  -D KNX_UART_NUM=1
  -D KNX_UART_RX_PIN=16
  -D KNX_UART_TX_PIN=17
  -D KNX_IP_WIFI

[env:develop_AZDelivery_DevKit_C_V4_TP]
extends = ESP32_develop, custom_ESP32, custom_develop, board_AZDelivery_DevKit_C_V4
build_flags =
  ${KNX_TP.build_flags}
  ${ESP32_develop.build_flags}
  ${custom_ESP32.build_flags}
  ${custom_develop.build_flags}
  ${board_AZDelivery_DevKit_C_V4.build_flags}
  -D DEVELOPMENT
 
[env:develop_AZDelivery_DevKit_C_V4_TP_USB]
extends = ESP32_UPLOAD_USB, env:develop_AZDelivery_DevKit_C_V4_TP

[env:develop_AZDelivery_DevKit_C_V4_IP]
extends = ESP32_develop, custom_ESP32, custom_develop, board_AZDelivery_DevKit_C_V4
build_flags =
  ${KNX_IP.build_flags}
  ${ESP32_develop.build_flags}
  ${custom_ESP32.build_flags}
  ${custom_develop.build_flags}
  ${board_AZDelivery_DevKit_C_V4.build_flags}
  -D DEVELOPMENT
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0


[env:develop_AZDelivery_DevKit_C_V4_IP_USB]
extends = ESP32_UPLOAD_USB, env:develop_AZDelivery_DevKit_C_V4_IP

; ------ Adafruit ESP32 Feather V2 ------
[board_Adafruit_Feather_ESP32_V2]
extends = ESP32_8MB
board = adafruit_feather_esp32_v2
build_flags =
  -D DEVICE_ADAFRUIT_ESP32_FEATHER_V2
  -D KNX_IP_WIFI

     

[env:develop_Adafruit_Feather_ESP32_TP_V2]
extends = ESP32_develop, custom_ESP32, custom_develop, board_Adafruit_Feather_ESP32_V2
build_flags =
  ${KNX_TP.build_flags}
  ${ESP32_develop.build_flags}
  ${custom_ESP32.build_flags}
  ${custom_develop.build_flags}
  ${board_Adafruit_Feather_ESP32_V2.build_flags}
  -D DEVELOPMENT

[env:develop_Adafruit_Feather_ESP32_V2_TP_USB]
extends = ESP32_UPLOAD_USB, env:develop_Adafruit_Feather_ESP32_TP_V2


[env:develop_RP2040]
extends = RP2040_custom_develop
build_flags =
  ${RP2040_custom_develop.build_flags}
  -D OPENKNX_LED_TIME=info3Led
  ; -D BOARD_SMARTMF_1TE_RP2040
  ; -D BOARD_MASIFI_V40
  -D DEVICE_REG1_BASE
  ; -D OKNXHW_REG1_CONTROLLER2040_V1
  ; -D OKNXHW_REG1_CONTROLLER2040
  ; -D BOARD_SIRSYDOM_PIPICO_BCU_CONNECTOR
  ; -D BOARD_MASIFI_PICO
  ; -D BOARD_MASIFI_HFPM_DEVEL2
  ; -D BOARD_ABTOOLS_FINGERPRINT_V13
  ;-D BOARD_ABTOOLS_HFPM_HLKLD2420
; debug_server = 
;     C:\Program Files\SEGGER\JLink\JLinkGDBServer
;     -singlerun
;     -nohalt
;     -if
;     SWD
;     -select
;     USB
;     -port
;     2331
;     -device
;     RP2040_M0_0
; debug_extra_cmds =   
;   monitor reset     # After sart reset the target
;   shell sleep 1     # wait a second,
;   cont              # then Continue (This will auto skip the init break)
;   ;load ;           # Load is not needed here


; Release

[env:release_SMARTMF_SENSORMODUL]
extends = RP2040_custom_releases_TP_16MB
build_flags =
  ${RP2040_custom_releases_TP_16MB.build_flags}
  -D DEVICE_SMARTMF_SENSORMODUL

[env:release_PiPico_BCU_Connector]
extends = RP2040_custom_releases_TP_2MB
build_flags =
  ${RP2040_custom_releases_TP_2MB.build_flags}
  -D DEVICE_PIPICO_BCU_CONNECTOR

[env:release_SMARTMF_1TE_REG]
extends = RP2040_custom_releases_TP_16MB
build_flags =
  ${RP2040_custom_releases_TP_16MB.build_flags}
  -D DEVICE_SMARTMF_1TE_REG

[env:release_OpenKNX_REG1_Controller2040]
extends = RP2040_custom_releases_TP_16MB
build_flags =
  ${RP2040_custom_releases_TP_16MB.build_flags}
  -D OKNXHW_REG1_CONTROLLER2040

[env:release_OpenKNX_REG1_BASE_V1]
extends = RP2040_custom_releases_TP_16MB
build_flags =
  ${RP2040_custom_releases_TP_16MB.build_flags}
  -D DEVICE_REG1_BASE
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=404
  -D OPENKNX_INFOLED3_DEFAULT=400


[env:release_Adafruit_Feather_ESP32_V2_TP]
extends = custom_release_ESP32, ESP32_8MB, board_Adafruit_Feather_ESP32_V2
build_flags =
   ${custom_release_ESP32.build_flags}  
   ${board_Adafruit_Feather_ESP32_V2.build_flags}
   ${KNX_TP.build_flags}
